RedAnt_2018/DUSite/urls.py
# coding:utf-8
from django import views
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

import DUSite.views
import RedAnt.personalAccount.views
from . import settings

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'DUSite.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/', admin.site.urls),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^index/', include('RedAnt.index.urls')),
    url(r'^teams/', include('RedAnt.teams.urls')),
    url(r'^courses/', include('RedAnt.courses.urls')),
    url(r'^manage/', include('RedAnt.userManage.urls')),
    url(r'^myaccount/', include('RedAnt.personalAccount.urls')),
    url(r'^forum/',include('RedAnt.forum.urls')),
    url(r'^media/(?P<path>.*)', views.static.serve, {'document_root': settings.MEDIA_ROOT }),
    url(r'^static/(?P<path>.*)', views.static.serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^(?P<path>.*)', views.static.serve, {'document_root': settings.STATIC_ROOT}),

]

RedAnt_2018/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

RedAnt_2018/RedAnt/models.py
# coding:utf-8
#
from django.db import models
from DjangoUeditor.models import UEditorField
from DjangoUeditor.commands import *
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch import receiver
from DUSite import settings
import os
from hashlib import md5


class log(models.Model):
    User = models.CharField(max_length=100)
    Content = models.CharField(max_length=100)
    Time = models.DateTimeField(auto_now=True)


class Introduction(models.Model):
    Name = models.CharField(u'名称', max_length=100)
    Content = UEditorField(u'内容', height=200, width=788, imagePath="introduction/", toolbars="besttome")


class ContactUs(models.Model):
    Name = models.CharField(u'名称', max_length=100)
    Content = UEditorField(u'内容', height=200, width=788, imagePath="contactus/", toolbars="besttome")


class Poster(models.Model):
    fileField = models.FileField(upload_to='index/poster/')


@receiver(post_delete, sender=Poster)
def delete_files(sender, instance, **kwargs):
    files = getattr(instance, 'fileField', '')
    if not files:
        return
    fname = os.path.join(settings.MEDIA_ROOT, str(files))
    if os.path.isfile(fname):
        os.remove(fname)


class Photo(models.Model):
    fileField = models.FileField(upload_to='photos/')


@receiver(post_delete, sender=Photo)
def delete_photos(sender, instance, **kwargs):
    files = getattr(instance, 'fileField', '')
    if not files:
        return
    fname = os.path.join(settings.MEDIA_ROOT, str(files))
    if os.path.isfile(fname):
        os.remove(fname)


class inviteCode(models.Model):
    code = models.CharField(max_length=100)
    ddl = models.CharField(max_length=100)


class ProjectTeam(models.Model):
    TeamName = models.CharField(u'项目组名称', max_length=100, null=True)
    Introduction = UEditorField(u'项目组简介', height=100, width=788, imagePath="team/", toolbars="besttome")
    OutofTime = models.BooleanField(u'历史项目组', default=False)
    GroupPhoto = models.ImageField(upload_to='photos/')


class Blog(models.Model):
    Name = models.CharField(u'名称', max_length=100)
    ImagePath = models.ImageField(null=True)
    Content = UEditorField(u'内容', height=200, width=788, imagePath="blog/",
                           toolbars="full")
    modify_time = models.DateTimeField(auto_now=True)
    Team = models.ForeignKey('ProjectTeam', null=True, on_delete=models.CASCADE, )


def get_upload_path(instance, filename):
    name = instance.Team.TeamName
    return 'Resourses/%s/%s' % (name, filename)


class LearningResources(models.Model):
    Team = models.ForeignKey('ProjectTeam', on_delete=models.CASCADE, )
    teamId = models.CharField(max_length=100, null=True)
    fileField = models.FileField(upload_to=get_upload_path)
    date = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=30, blank=True, null=True)


@receiver(post_delete, sender=LearningResources)
def delete_upload_files(sender, instance, **kwargs):
    files = getattr(instance, 'fileField', '')
    if not files:
        return
    fname = os.path.join(settings.MEDIA_ROOT, str(files))
    if os.path.isfile(fname):
        os.remove(fname)


class Post(models.Model):
    postedBy = models.ForeignKey(User, on_delete=models.CASCADE)
    postNum = models.CharField(max_length=100)
    name = models.CharField(u'名称', max_length=100)
    modify_time = models.DateTimeField(auto_now=True)


class lPost(models.Model):
    postedBy = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    Content = UEditorField(u'回复', height=200, width=788, imagePath="forum/",
                           toolbars="besttome")
    modify_time = models.DateTimeField(auto_now=True)
    post = models.ForeignKey('post', null=True, on_delete=models.CASCADE, )


class Course(models.Model):
    Name = models.CharField(u'课程名称', max_length=100, null=True)
    Introduction = UEditorField(u'课程简介', height=100, width=788, imagePath="course/", toolbars="besttome")


class ZhangJieSmallPic(models.Model):
    file = models.FileField(upload_to=get_upload_path)
    zhangJiesmall = models.ForeignKey('ZhangJieSmall', on_delete=models.CASCADE)

    @staticmethod
    def save_file(f):
        m = md5()
        for i in f.chunks():
            m.update(i)
        name = m.hexdigest() + '.' + f.name.split('.')[-1]
        fp = os.path.join(
            os.path.dirname(__file__),
            '../Media/course/%s' % name
        )
        if not os.path.exists(fp):
            with open(fp, 'wb+') as fw:
                for i in f.chunks():
                    fw.write(i)
        return name

    def path(self):
        return '/Media/course/%s' % str(self.file)

    def __str__(self):
        return self.file.path


@receiver(post_delete, sender=ZhangJieSmallPic)
def deletePPT(sender, instance, **kwargs):
    files = getattr(instance, 'file', '')
    if not files:
        return
    fname = os.path.join(
        os.path.dirname(__file__),
        '..../Media/course/%s' % str(files)
    )
    if os.path.isfile(fname):
        os.remove(fname)


class ZhangJieSmall(models.Model):
    name = models.CharField(max_length=21)
    video = models.FileField(upload_to=get_upload_path)
    video_desc = models.CharField(max_length=1024, default='', blank=True)
    content = models.CharField(max_length=2048, default='', blank=True)
    zhangJie = models.ForeignKey('ZhangJie', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ZhangJie(models.Model):
    kecheng = models.CharField(max_length=21)
    name = models.CharField(max_length=21)
    details = models.ManyToManyField(ZhangJieSmall)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

RedAnt_2018/DUSite/views.py
from django import views
from django.http import HttpResponseRedirect
import urllib.parse


def get_media(request, path):
    url = "/Media/" + path
    return HttpResponseRedirect(url)


def get_static(request, path):
    url = "/Static/" + path
    return HttpResponseRedirect(url)

RedAnt_2018/DUSite/templates/course/content.html
     <!--course-->
        <div class="course">
            <div class="intr">
                <div class="couvideo" id="couvideo">
                    <div>
                    	<div class="coutitle">
                    		<h3>{{ zjsmall.name }}</h3>
                    	</div>
                        {% if perms.auth.change_couser %}
                        <button class="rightBottom" onclick="alertInfoWithJump('确认删除此章节？','?zjs_id={{ zjsmall.id }}&operating=delzjs')"><i class="fa fa-trash"></i>删除
                        </button>
                        <button class="rightBottom" onclick="window.location.href='/courses/zhangjie_small_add?zj_id={{ zj.id }}&kecheng={{ course.id }}&zj={{ zj.name }}&zjs_id={{ zjsmall.id }}&type=video&zjsmall={{ zjsmall.name }}' " id="videoEdit"><i class="fa fa-pencil"></i>编辑
                        </button>
                        <button class="rightBottom" onclick=" window.location.href='/courses/zhangjie_small_add?zj_id={{ zj.id }}&kecheng={{ course.id }}&zj={{ zj }}&zjs_id={{ zjsmall.id }}&type=content&zjsmall={{ zjsmall.name }}' " id="slidsEdit" >
                            <i class="fa fa-pencil"></i>编辑
                        </button>
                        {% endif %}
                        <div style="margin-top: 10px;margin-left: 5%;">  
                            <button onclick="video()" class="contButton">视频</button>
                            <button onclick="slids()" class="contButton">课件</button>
                            <script type="text/javascript">
                                function video(){
                                    document.getElementById("video").style.display='block';
                                    document.getElementById("slids").style.display='none';
                                    document.getElementById("videoEdit").style.display='inline-block';
                                    document.getElementById("slidsEdit").style.display='none';
                                }
                                function slids(){
                                    var x=document.getElementById("video").style.display='none';
                                    var y=document.getElementById("slids").style.display='block';
                                    document.getElementById("videoEdit").style.display='none';
                                    document.getElementById("slidsEdit").style.display='inline-block';
                                }
                               
                            </script>

                            
                        </div>
                    </div>
                    <div class="video" id="video">
                        <p>{{ zjsmall.video_desc }}</p>
                            <video controls preload="meta" width="640" height="350" poster="/static/images/poster.png" data-setup="{}">
                                <source src="/media/course/{{ zjsmall.video}}" type="video/mp4">
        						<source src="/media/course/{{ zjsmall.video}}" type="video/webm">
        						<source src="/media/course/{{ zjsmall.video}}" type="video/ogg">
                            </video>
                            <hr>
                    </div>
                    <!--课件播放-->
                    <div class="slids" id="slids">
                        <div>
                            
                            <p>
                                {{ zjsmall.content }}
                            </p>
                        </div>
                        <div id="wheel-container" class="wheel-container">
                            <div id="wheel" class="wheel">
                                <div id="photo" class="photo">
                                    <div id="pre" class="pre">
                                        <i class="fa fa-angle-left"></i>
                                    </div>
                                    {% for img in pics %}
                                        <img src="/media/course/{{ img.file}}" alt="轮播图片">
                                    {% endfor %}
                                    <div id="after" class="after">
                                        <i class="fa fa-angle-right"></i>
                                    </div>
                                </div>
                                <div id="wheel-spot" class="wheel-spot">
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>
            </div>
            
            <div class="clear"></div>
    
         <br><br><br>

         </div>
         
        
       

RedAnt_2018/DUSite/templates/course/courseMain.html
<style>
    #submit{width: 60px;border-radius: 5px; background-color: deepskyblue;border: none; color: white; height: 30px;}
</style>

 <!--course-->
<div class="course">
    <div class="intr">
        <div class="couvideo" id="couvideo">
        <div>
            <div class="coutitle">
                <h3>{{ course.Name }} </h3>
            </div>
            {% if perms.RedAnt.delete_course %}
                <button onclick="alertInfoWithJump2('确定删除此课程吗？','?operating=delete')" class="edit rightBottom"><i class="fa fa-trash"></i>删除</button>{% endif %}
            {% if perms.RedAnt.change_course %}
                 <button onclick="window.location.href='edit/' " class="edit rightBottom"><i class="fa fa-pencil"></i>编辑</button>
            {% endif %}
             <p>
            {% autoescape off %}
                {{ course.Introduction }}
             {% endautoescape %}
            </p>
        </div>
    </div>
    <div class="clear"></div>
 </div>
</div>
<br><br><br>

RedAnt_2018/DUSite/templates/course/footer.html
<footer>
  <div class="">
  <hr>
    <p> Copyright 红蚂蚁实验室</p>
  <hr>
  </div>
</footer>

    <script type="text/javascript" src="/static/js/signIn.js"></script>
    <script type="text/javascript" src="/static/js/contact.js"></script>
    <script type="text/javascript" src="/static/js/wheel1.js"></script>
    <script type="text/javascript" src="/static/js/news.js"></script>
    <script type="text/javascript" src="/static/js/alertModel.js"></script>
    <script type="text/javascript">
    jQuery("#jquery-accordion-menu").jqueryAccordionMenu();
    </script>
    </body>
  </div>
  <!--模态框包含确认键-->
         <div class="model-alertInfo" id="model-alertInfo">
            <div class="model-container">
                <div class="model-head">
                    <span class="model-title">{{course.Name}}</span>
                    <i class="fa fa-close"></i>
                </div>
                <div class="model-body">
                    <h3 class="message"></h3>
                </div>
                <div class="model-end">
                    <div class="btn get">确 认</div>
                </div>
            </div>
        </div>
        <!--alarm警告框-->
        <div class="model-alertInfo" id="model-alertInfo_0">
            <div class="model-container">
                <div class="model-head">
                    <span class="model-title">{{course.Name}}</span>
                </div>
                <div class="model-body">
                    <h3 class="message"></h3>
                </div>
            </div>
        </div>
      
</html>

RedAnt_2018/DUSite/templates/course/head.html
<!DOCTYPE html>
<html>
  <head>
    <title>课程展示</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <link rel="stylesheet" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.css">

    <link rel="stylesheet" type="text/css" href="/static/css/home.css">

    <script src="/static/js/jquery-1.8.3.min.js"></script>
    <script src="/static/js/jquery.tiles.js"></script>
    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/jquery.tiles.min.css">
    <link href="/static/css/jquery-accordion-menu.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/static/css/home1com.css">
    <link rel="stylesheet" type="text/css" href="/static/css/wheel1.css">
    <link rel="stylesheet" type="text/css" href="/static/css/nav.css">
    <link rel="stylesheet" type="text/css" href="/static/css/coursebase.css">
    <link rel="stylesheet" type="text/css" href="/static/css/video.css">
    <link rel="stylesheet" type="text/css" href="/static/css/footer.css">
    <!--sideBar-->
    
    <link href="/static/css/font-awesome.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/static/css/personalCenter.css">
    <link rel="stylesheet" type="text/css" href="/static/css/alertModel.css">

    <script src="/static/js/jquery-accordion-menu.js" type="text/javascript"></script>
    <script type="text/javascript"></script>
</head>


<body>
    {% include 'topBar.html' %}

RedAnt_2018/DUSite/templates/course/sidebar.html
<div class="jquery-accordion-menu-con">
<div id="jquery-accordion-menu" class="jquery-accordion-menu red">
    <div class="jquery-accordion-menu-header" id="form">
        <span>{{course.Name}}</span>
    </div>
    <ul id="demo-list">
        {% for zj in zjs %}
        <li><a href="#"><i class="fa fa-calendar"></i>{{ zj.name }} </a>
            <ul class="submenu">
                {% for zjs in zj.details.all %}
                    <li>
                        <a href="/courses/major={{ course.id }}?zjs_id={{ zjs.id }}">{{ zjs.name }} </a>
                    </li>
                {% endfor %}
                {% if perms.auth.change_couser %}
                <li>
                    <a href="/courses/zhangjie_small_add?zj_id={{ zj.id }}&kecheng={{ course.id }}&zj={{ zj.name }}" class="addPart"><button class="addSlides">添加子章节</button></a> 

                </li>
                <li>
                    <a href="/courses/zj_del?zj_id={{ zj.id }}&kecheng={{ course.id }}&zj={{ zj.name }}" class="addPart"><button class="addSlides">删除此章节</button></a>
                </li>
                {% endif %}
            </ul>
        </li>
        {% endfor %}
    <li>
        <a href="/courses/zhangjie_add?kecheng={{ course.id }}"><i class="fa fa-calendar"></i>新增章节 </a>
    </li>
</ul>
</div>
</div>

RedAnt_2018/DUSite/templates/course/zj_add.html
<style>
    #submit{width: 60px;border-radius: 5px; background-color: deepskyblue;border: none; color: white; height: 30px;}
</style>
<div class="jquery-accordion-menu-con">
    <div id="jquery-accordion-menu" class="jquery-accordion-menu red">

                    <div class="jquery-accordion-menu-header" id="form">
                        <a href="/courses/major={{ course.id }}/" style="color: inherit;">{{ course.Name }}</a>
                    </div>
                    <ul id="demo-list">
                        <li>
                            <a href=""><i class="fa fa-calendar"></i>新增章节 </a>
                        </li>
                    </ul>
    </div>
</div>
<div class="main-container" >
    <div style="margin-left: 450px;">
        <form action="" enctype="multipart/form-data" method="post">
            <table>
                <colsgroup>
                    <col style="width: 120px;">
                    <col>
                </colsgroup>
                <tr >
                    <td>
                        <span>课程名</span>
                    </td>
                    <td>
                        {{ course.Name }}
                        <input type="hidden" name="kecheng" value="{{ kecheng }}">
                    </td>
                </tr>
                <tr >
                    <td>
                        <span>章节名</span>
                    </td>
                    <td>
                        <input type="text" name="name" id="name" placeholder="请输入章节名">
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                        <button id="submit" type="submit" >提交</button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

RedAnt_2018/DUSite/templates/course/zjsmall_add.html
<style>
    #submit{width: 60px;border-radius: 5px; background-color: deepskyblue;border: none; color: white; height: 30px;}
</style>
<div class="main-container" >
    <div style="margin-left: 25%;">
        <form action="/courses/zhangjie_small_add" enctype="multipart/form-data" method="post" style="border: 1px solid #ddd;margin:5%; padding: 10px; margin-top: 50px;">
            <table>
                <colsgroup>
                    <col style="width: 120px;">
                    <col style="min-width: 400px;">
                </colsgroup>
                <tr >
                    <td>
                        
                    </td>
                    <td>
                        {% if zjsmall %}
                            {{ zj }} - {{ zjsmall }} - 修改
                        <input type="hidden" name="zjs_id" value="{{ zjs_id }}">
                        {% else %}
                            {{ zj }} - 添加子章节
                        {% endif %}
                        <input type="hidden" name="kecheng" value="{{ kecheng }}">
                        <input type="hidden" name="zj" value="{{ zj }}">
                    </td>
                </tr>
            {% if not type_ %}
                <tr >
                    <td>
                        <span>章节名</span>
                    </td>
                    <td>
                        <input type="text" name="name" id="name" placeholder="请输入章节名" value="默认章节名" style="width: 100%;">
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td><span style="color: red">注意</span></td>
                    <td><span style="color: red">文件不上传则不会进行删除修改</span></td>
                </tr>
            {% endif %}
            {% if not type_ or type_ == 'video' %}
                <tr >
                    <td>
                        <span>章节视频</span>
                    </td>
                    <td>
                        <input type="file" name="video" style="font-size: 14px;">
                    </td>
                </tr>
                <tr >
                    <td>
                        <span>视频描述</span>
                    </td>
                    <td>
                        <textarea name="video_desc" id="" style="width: 100%" rows="10">{{ zjsmall.video_desc }}</textarea>
                    </td>
                </tr>
            {% endif %}
            {% if not type_ or type_ == 'content' %}
                <tr >
                    <td>
                        <span>章节内容</span>
                    </td>
                    <td>
                        <textarea name="content" id="" style="width: 100%" rows="10">{{ zjsmall.content }}</textarea>
                    </td>
                </tr>
                <tr >
                    <td>
                        <span>图片课件</span>
                    </td>
                    <td>
                        <input type="file" name="pics" multiple="multiple" value="可以选择多个文件">
                    </td>
                </tr>
            {% endif %}
                <tr>
                    
                </tr>
            </table>
            <br>
            <button id="submit" type="submit" style="position: relative;left: 50%;" onclick="alertInfoWithJump0('正在进行提交，请勿关闭页面，否则将提交失败')">提交</button>
        </form>
    </div>
</div>