RedAnt_2018/DUSite/urls.py
# coding:utf-8
from django import views
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

import DUSite.views
import RedAnt.personalAccount.views
from . import settings

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'DUSite.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/', admin.site.urls),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^index/', include('RedAnt.index.urls')),
    url(r'^teams/', include('RedAnt.teams.urls')),
    url(r'^courses/', include('RedAnt.courses.urls')),
    url(r'^manage/', include('RedAnt.userManage.urls')),
    url(r'^myaccount/', include('RedAnt.personalAccount.urls')),
    url(r'^forum/',include('RedAnt.forum.urls')),
    url(r'^media/(?P<path>.*)', views.static.serve, {'document_root': settings.MEDIA_ROOT }),
    url(r'^static/(?P<path>.*)', views.static.serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^(?P<path>.*)', views.static.serve, {'document_root': settings.STATIC_ROOT}),

]

RedAnt_2018/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

RedAnt_2018/RedAnt/forum/urls.py
from django.conf.urls import include, url
import RedAnt.forum.views as views

urlpatterns = [
    url(r'post/', views.post),
    url(r'forum=(?P<name>.*)/page=(?P<page>[0-9]+)/delete=(?P<post>[0-9]+)/', views.deleteLpost),
    url(r'forum=(?P<name>.*)/page=(?P<page>[0-9]+)/delete/', views.delete),
    url(r'forum=(?P<name>.*)/page=(?P<page>[0-9]+)/', views.forum),
    url(r'forum=(?P<name>.*)/', views.forumJump),
    url(r'post_tol_page', views.postTolPage),
    url(r'post_forum_ajax', views.postForumAjax),
    url(r'', views.index),
]

RedAnt_2018/RedAnt/models.py
# coding:utf-8
#
from django.db import models
from DjangoUeditor.models import UEditorField
from DjangoUeditor.commands import *
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch import receiver
from DUSite import settings
import os
from hashlib import md5


class log(models.Model):
    User = models.CharField(max_length=100)
    Content = models.CharField(max_length=100)
    Time = models.DateTimeField(auto_now=True)


class Introduction(models.Model):
    Name = models.CharField(u'名称', max_length=100)
    Content = UEditorField(u'内容', height=200, width=788, imagePath="introduction/", toolbars="besttome")


class ContactUs(models.Model):
    Name = models.CharField(u'名称', max_length=100)
    Content = UEditorField(u'内容', height=200, width=788, imagePath="contactus/", toolbars="besttome")


class Poster(models.Model):
    fileField = models.FileField(upload_to='index/poster/')


@receiver(post_delete, sender=Poster)
def delete_files(sender, instance, **kwargs):
    files = getattr(instance, 'fileField', '')
    if not files:
        return
    fname = os.path.join(settings.MEDIA_ROOT, str(files))
    if os.path.isfile(fname):
        os.remove(fname)


class Photo(models.Model):
    fileField = models.FileField(upload_to='photos/')


@receiver(post_delete, sender=Photo)
def delete_photos(sender, instance, **kwargs):
    files = getattr(instance, 'fileField', '')
    if not files:
        return
    fname = os.path.join(settings.MEDIA_ROOT, str(files))
    if os.path.isfile(fname):
        os.remove(fname)


class inviteCode(models.Model):
    code = models.CharField(max_length=100)
    ddl = models.CharField(max_length=100)


class ProjectTeam(models.Model):
    TeamName = models.CharField(u'项目组名称', max_length=100, null=True)
    Introduction = UEditorField(u'项目组简介', height=100, width=788, imagePath="team/", toolbars="besttome")
    OutofTime = models.BooleanField(u'历史项目组', default=False)
    GroupPhoto = models.ImageField(upload_to='photos/')


class Blog(models.Model):
    Name = models.CharField(u'名称', max_length=100)
    ImagePath = models.ImageField(null=True)
    Content = UEditorField(u'内容', height=200, width=788, imagePath="blog/",
                           toolbars="full")
    modify_time = models.DateTimeField(auto_now=True)
    Team = models.ForeignKey('ProjectTeam', null=True, on_delete=models.CASCADE, )


def get_upload_path(instance, filename):
    name = instance.Team.TeamName
    return 'Resourses/%s/%s' % (name, filename)


class LearningResources(models.Model):
    Team = models.ForeignKey('ProjectTeam', on_delete=models.CASCADE, )
    teamId = models.CharField(max_length=100, null=True)
    fileField = models.FileField(upload_to=get_upload_path)
    date = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=30, blank=True, null=True)


@receiver(post_delete, sender=LearningResources)
def delete_upload_files(sender, instance, **kwargs):
    files = getattr(instance, 'fileField', '')
    if not files:
        return
    fname = os.path.join(settings.MEDIA_ROOT, str(files))
    if os.path.isfile(fname):
        os.remove(fname)


class Post(models.Model):
    postedBy = models.ForeignKey(User, on_delete=models.CASCADE)
    postNum = models.CharField(max_length=100)
    name = models.CharField(u'名称', max_length=100)
    modify_time = models.DateTimeField(auto_now=True)


class lPost(models.Model):
    postedBy = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    Content = UEditorField(u'回复', height=200, width=788, imagePath="forum/",
                           toolbars="besttome")
    modify_time = models.DateTimeField(auto_now=True)
    post = models.ForeignKey('post', null=True, on_delete=models.CASCADE, )


class Course(models.Model):
    Name = models.CharField(u'课程名称', max_length=100, null=True)
    Introduction = UEditorField(u'课程简介', height=100, width=788, imagePath="course/", toolbars="besttome")


class ZhangJieSmallPic(models.Model):
    file = models.FileField(upload_to=get_upload_path)
    zhangJiesmall = models.ForeignKey('ZhangJieSmall', on_delete=models.CASCADE)

    @staticmethod
    def save_file(f):
        m = md5()
        for i in f.chunks():
            m.update(i)
        name = m.hexdigest() + '.' + f.name.split('.')[-1]
        fp = os.path.join(
            os.path.dirname(__file__),
            '../Media/course/%s' % name
        )
        if not os.path.exists(fp):
            with open(fp, 'wb+') as fw:
                for i in f.chunks():
                    fw.write(i)
        return name

    def path(self):
        return '/Media/course/%s' % str(self.file)

    def __str__(self):
        return self.file.path


@receiver(post_delete, sender=ZhangJieSmallPic)
def deletePPT(sender, instance, **kwargs):
    files = getattr(instance, 'file', '')
    if not files:
        return
    fname = os.path.join(
        os.path.dirname(__file__),
        '..../Media/course/%s' % str(files)
    )
    if os.path.isfile(fname):
        os.remove(fname)


class ZhangJieSmall(models.Model):
    name = models.CharField(max_length=21)
    video = models.FileField(upload_to=get_upload_path)
    video_desc = models.CharField(max_length=1024, default='', blank=True)
    content = models.CharField(max_length=2048, default='', blank=True)
    zhangJie = models.ForeignKey('ZhangJie', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ZhangJie(models.Model):
    kecheng = models.CharField(max_length=21)
    name = models.CharField(max_length=21)
    details = models.ManyToManyField(ZhangJieSmall)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

RedAnt_2018/RedAnt/forms.py
# coding:utf-8
from django import forms
from DjangoUeditor.widgets import UEditorWidget
from DjangoUeditor.forms import UEditorField, UEditorModelForm
from .models import Blog, ProjectTeam, lPost, Course


class teamForm(UEditorModelForm):
    class Meta:
        model = ProjectTeam
        fields = ('TeamName', 'Introduction', 'OutofTime')
        widgets = {
            "TeamName": forms.TextInput(attrs={"style": "width:788px;"}),
            # 直接设置style或者某项属性改变样式，记得字典格式，赋值给attrs
        }


class myUEditorModelForm(UEditorModelForm):
    class Meta:
        model = Blog
        fields = ('Name', 'Content')
        widgets = {
            "Name": forms.TextInput(attrs={"style": "width:788px;"}),
            # 直接设置style或者某项属性改变样式，记得字典格式，赋值给attrs
        }


class postForm(UEditorModelForm):
    class Meta:
        model = lPost
        fields = ('Content',)


class FileUploadForm(forms.Form):
    file = forms.FileField(label='图片')

    class Meta:
        widgets = {
            "file": forms.TextInput(attrs={"class": "files"}),
            # 直接设置style或者某项属性改变样式，记得字典格式，赋值给attrs
        }


class CourseForm(UEditorModelForm):
    class Meta:
        model = Course
        fields = ('Name', 'Introduction')


class smallCourseForm(UEditorModelForm):
    class Meta:
        model = Course
        fields = ('Introduction',)

RedAnt_2018/DUSite/views.py
from django import views
from django.http import HttpResponseRedirect
import urllib.parse


def get_media(request, path):
    url = "/Media/" + path
    return HttpResponseRedirect(url)


def get_static(request, path):
    url = "/Static/" + path
    return HttpResponseRedirect(url)

RedAnt_2018/RedAnt/forum/views.py
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, render
import urllib.request
from RedAnt.forms import postForm, myUEditorModelForm
from RedAnt.models import Post, lPost, ProjectTeam, Course
from django.contrib.auth.models import User
import math
import json


def index(request):
    posts = Post.objects.all().order_by('-modify_time')
    teams = ProjectTeam.objects.all()
    courses = Course.objects.all()
    return render(request, 'forum.html', {'teams': teams, 'posts': posts, 'courses': courses})


def post(request):
    if request.method == 'POST':
        form = myUEditorModelForm(request.POST)
        if form.is_valid():
            lpost = lPost()
            post = Post()
            blog = form.save()
            lpost.Content = blog.Content
            post.postedBy = request.user
            post.name = blog.Name
            post.postNum = 1
            lpost.postedBy = request.user
            post.save()
            lpost.post = post
            lpost.save()
            blog.delete()
            url = '/forum/'
            return HttpResponseRedirect(url)
    else:
        form = myUEditorModelForm()
        teams = ProjectTeam.objects.all()
        courses = Course.objects.all()
        return render(request, 'forums.html', {'teams': teams, 'form': form, 'courses': courses})


def forum(request, name, page):
    if request.method == 'POST':
        form = postForm(request.POST)
        if form.is_valid():
            temp = form.save()
            lpost = temp
            lpost.post = Post.objects.get(id=name)
            lpost.post.postNum = str(int(lpost.post.postNum) + 1)
            lpost.post.save()
            lpost.postedBy = request.user
            temp.delete()
            lpost.save()
        url = request.get_full_path()
        return HttpResponseRedirect(url)
    else:
        lposts = lPost.objects.filter(post_id=name).order_by('modify_time')
        lpost = lposts[0]
        lposts = lposts[1:]
        post = postForm()
        name = Post.objects.get(id=name).name
        teams = ProjectTeam.objects.all()
        courses = Course.objects.all()
        return render(request, 'forumContent.html',
                      {'teams': teams, 'lposts': lposts, 'lpost': lpost, 'post': post, 'name': name,
                       'courses': courses})


def forumJump(request, name):
    url = request.get_full_path() + 'page=1/'
    return HttpResponseRedirect(url)


def deleteLpost(request, name, page, post):
    lPost.objects.get(id=post).delete()
    post = Post.objects.get(id=name)
    post.postNum = str(int(post.postNum) - 1)
    post.save()
    url = '/forum/forum=' + name + '/'
    return HttpResponseRedirect(url)


def delete(request, name, page):
    Post.objects.get(id=name).delete()
    url = '/forum/'
    return HttpResponseRedirect(url)


def postTolPage(request):
    post = Post.objects.all()
    tol = len(post)
    page = math.ceil(tol / 10)
    data = {'tol_page': page}
    return JsonResponse(data)


def postForumAjax(request):
    page = int(request.POST["page"])
    posts = Post.objects.all().order_by('-modify_time')
    resp = []
    for i in range((page - 1) * 3, page * 3):
        if i < len(posts):
            resp.append({'id': posts[i].id, 'name': posts[i].name,
                         'month': posts[i].modify_time.month, 'day': posts[i].modify_time.day,
                         'postNum': posts[i].postNum, 'user': posts[i].postedBy.username})
    return HttpResponse(json.dumps(resp), content_type="application/json")

RedAnt_2018/DUSite/templates/course.html
{% include 'course/head.html' %}

<div><div class="wrapper">
<!--sidebar-->
{% include 'course/sidebar.html' %}
<!--introduce-->
{% include 'course/courseMain.html' %}
</div></div>
{% include 'course/footer.html' %}

RedAnt_2018/DUSite/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>首页</title>
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" /> -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css">
    <!-- [if lt IE 9]><script src="js/html5.js"></script><![endif] -->
    <script src="/static/js/jquery-1.8.3.min.js"></script>
    <script src="/static/js/jquery.tiles.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/alertModel.css">
    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/jquery.tiles.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/home.css">
    <link rel="stylesheet" type="text/css" href="/static/css/wheel.css">
    <link rel="stylesheet" type="text/css" href="/static/css/nav.css">
    <link rel="stylesheet" type="text/css" href="/static/css/personalCenter.css">
    <link rel="stylesheet" type="text/css" href="/static/css/cornerTop.css">
</head>
<body>
{% include 'topBar.html' %}
<!-- 轮播图片 -->
<div id="wheel-container" class="wheel-container">
    <div class="bac-lim">
        <div id="wheel" class="wheel">
            <div id="photo" class="photo">
                <div id="pre" class="pre">
                    <i class="fa fa-angle-left"></i>
                </div>
                {% for poster in posters %}
                    <img src='/media/{{ poster.fileField }}' alt="轮播图片">
                {% endfor %}
                <div id="after" class="after">
                    <i class="fa fa-angle-right"></i>
                </div>
            </div>
            <div id="wheel-spot" class="wheel-spot">
                {% for poster in posters %}
                    <div class="spot"></div>
                {% endfor %}
            </div>
        </div>
        {% if perms.auth.change_user %}
            <button class="btn" onclick="window.location.href='changePoster/'">编辑图片</button>
        {% endif %}
    </div>
</div>
<div class="limit">
    <!-- Project -->
    <div class="project">
        <div class="intr">
            <div class="side-fixed">
                <div class="intr-project">
                    <span>{{ introduction.Name }}</span>
                    <p>
                        {% autoescape off %}
                            {{ introduction.Content }}
                        {% endautoescape %}
                        {% if user.is_superuser %}
                            <button class="btn edit" onclick="window.location.href='introduce/'">编辑</button>
                        {% endif %}
                    </p>
                </div>
            </div>
            <div class="img-group">
                {% for team in teams %}
                    {% if team.OutofTime is False %}
                        <div class="proimg" id="proimg">
                            <div>
                                <img src=/media/{{ team.GroupPhoto }}>
                                <div class="back-img-hover" id="back-img-hove">
                                    <div class="hover-eff">
                                        <h2>{{ team.TeamName }}</h2>
                                        <p>
                                            {% autoescape off %}
                                                {{ team.Introduction }}
                                            {% endautoescape %}
                                        </p>
                                        <a href="/teams/major={{ team.id }}/">了解更多</a>
                                        {% if user.first_name == team.TeamName or user.is_superuser %}
                                            {% if perms.RedAnt.change_projectteam %}
                                                <a href="/teams/major={{ team.id }}/changeImg/">更换图片</a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="contact" id="contact">
    <div class="title-contact">{{ contact.Name }}</div>
    <div class="line-con">
        <div class="line"></div>
    </div>
    <div class="intr-contact">
        <p>
            {% autoescape off %}
                <span class="edit-target">{{ contact.Content }}</span>
            {% endautoescape %}
            <br>
            {% if user.is_superuser %}
                <button class="btn edit" onclick="window.location.href= 'contactUs/'">编辑</button>
            {% endif %}
        </p>
    </div>
    <!-- <div id="u189" class="ax_default primary_button" data-label="send">
        <div id="u190" class="text" style="visibility: visible;">
        <p id="contactUs"><span>给我们发邮件</span></p>
        </div>
    </div> -->
    <div class="send-email">
        <form id="send-email">
            <div class="body-line">
                <input id="from-mail" type="text" placeholder="请填写你的邮箱" onchange="checkFromMail(this)"/>
                <i class="check fa fa-check" id="check-from-mail"></i>
            </div>
            <div class="body-line">
                <input id="from-name" type="text" placeholder="填写你的真实姓名"/>
                <!-- <i class="check fa fa-check" id="check-psw"></i> -->
            </div>
            <div class="body-line">
                <textarea id="from-content" type="text" placeholder="写下你的疑问或心声！"></textarea>
                <!-- <i class="check fa fa-check" id="check-psw"></i> -->
            </div>
            <input type="submit" name="send" value="发 送" id="send">
        </form>
    </div>
</div>
<div class="model-alertInfo" id="model-alertInfo">
    <div class="model-container">
        <div class="model-head">
            <span class="model-title">联系我们</span>
            <i class="fa fa-close"></i>
        </div>
        <div class="model-body">
            <h3 class="message"></h3>
        </div>
        <div class="model-end">
            <div class="btn get">确 认</div>
            <!-- <div class="btn shut">关 闭</div> -->
        </div>
    </div>
</div>
<div class="corner-top">
    <button class="CornerButton" onclick="backTotop()" aria-lable="回到顶部" type="button" data-tooltip="回到顶部"
            data-tooltip-position="left" id="CornerButton">
        <svg title="回到顶部" class="Backtotop" FILL="currentColor" viewBox="0 0 24 24" width="24" height="24">
            <path d="M 16.036 19.59 a 1 1 0 0 1 -0.997 0.995 H 9.032 a 0.996 0.996 0 0 1 -0.997 -0.996 v -7.005 H 5.03 c -1.1 0 -1.36 -0.633 -0.578 -1.416 L 11.33 4.29 a 1.003 1.003 0 0 1 1.412 0 l 6.878 6.88 c 0.782 0.78 0.523 1.415 -0.58 1.415 h -3.004 v 7.005 Z">
            </path>
        </svg>
    </button>
</div>

<script type="text/javascript" src="/static/js/alertModel.js"></script>
<script type="text/javascript" src="/static/js/signIn.js"></script>
<script type="text/javascript" src="/static/js/contact.js"></script>
<script type="text/javascript" src="/static/js/wheel.js"></script>
<script type="text/javascript" src="/static/js/news.js"></script>
<script type="text/javascript" src="/static/js/backTop.js"></script>
<footer>
    <div>
        <hr>
        <p> Copyright 红蚂蚁实验室</p>
        <hr>
    </div>
</footer>
</body>
</html>

RedAnt_2018/DUSite/templates/topBar.html
<script>
            window.onload=function(){
                var i=document.getElementsByTagName('input').length;
                var input=$("#model .model-body input");
                var i=input.length;
                for(var n=0;n<i-1;n++){
                    input[n].value='';
                    $("#model .model-body i").css("opacity","0");
                }
            }
</script>
<div class="Top-bar">
    <div class="top-icon"><img src="/static/images/LOGO2.png" alt="实验室图标"></div>
    <div class="LabSlogan">
        <span> 遇到问题立即沟通 !<br></span>
        <span class="secondslo"> 我是最后负责人 !</span>
    </div>
    <div class="enter">
        {% if user.is_authenticated %}
            <div class="person">
                    <a href="/myaccount/">
                        <img src="/media/{{ user.last_name }}" alt="用户头像">
                    </a>
                    <span class="drop-menu" id="drop-menu">
                        <a href="/myaccount/">
                            个人中心
                        </a>
                    </span>
                    <span class="drop-menu" id="drop-menu">
                        <a href="/index/logout/">
                            注销
                        </a>
                    </span>
            </div>
        {% else %}
            <span class="spe-enlight"><a href="javascript:void(0)" id="sign-btn">登 录</a></span>
            <span> / </span>
            <span class="spe-enlight"><a href="/index/sign_up/">注 册</a></span>
        {% endif %}
    </div>
</div>
<div class="model-hide" style="display: none;" id="model">
    <div class="model-container">
        <div class="model-head">
            <span class="model-title">登 录</span>
            <i class="fa fa-close"></i>
        </div>
        <div class="model-body">
            <div class="sign-in">
                <form id="sign-in">
                    <div class="body-line">
                        <label for="mail">邮 箱 : </label>
                        <input id="mail" class="input1" type="text" placeholder="请输入登录邮箱" onchange="checkMail(this)"  autocomplete="close"/>
                        <!-- <i class="check fa fa-close" id="check-mail"></i> -->
                    </div>
                    <div class="body-line">
                        <label for="psw">密 码 : </label>
                        <input id="psw" class="input2" type="password" placeholder="请输入登录密码" onchange="checkPsw(this)" autocomplete="close" />
                        <!-- <i class="check fa fa-check" id="check-psw"></i> -->
                    </div>
                    <input type="submit" name="submit" value="登 录" id="login">
                </form>
            </div>
        </div>
        <div class="model-end">
            <a href="javascript:void(0)" id="forget">忘记密码？</a>
        </div>
    </div>
</div>
<div class="model-hide" style="display: none;" id="forget-model">
    <div class="model-container">
        <div class="model-head">
            <span class="model-title">忘记密码</span>
            <i class="fa fa-close"></i>
        </div>
        <div class="model-body">
            <div class="sign-in">
                <form id="sign-in">
                    <div class="body-line">
                        <label for="mail">邮 箱 : </label>
                        <input id="mail" class="input1" type="text" placeholder="请输入登录邮箱" onchange="checkMail(this)"  autocomplete="close"/>
                        <!-- <i class="check fa fa-close" id="check-mail"></i> -->
                    </div>
                    <input type="submit" name="submit" value="找回密码" id="findBack">
                </form>
            </div>
        </div>
        <div class="model-end">
            <a href="javascript:void(0)" id="signIn">登录</a>
        </div>
    </div>
</div>
<!-- 导航栏 -->
<nav role="navigation">
    <div class="region region-navigation">
        <ul class="navbar-menu">
            <li class="first-leaf thisleaf"><a href="/index/" data-target="#" class="dropdown-toggle" data-toggle="dropdown">首 &nbsp;页</a>
            </li>
            <li class="dropdown"><a href="javascript:void(0);">项目组<span class="caret"></span></a>
                <ul class="dropdown-menu pull-right">
                {% for team in teams %}
                    {% if team.OutofTime is False%}
                        <li class="dropdownmenu"><a href="/teams/major={{ team.id }}/">{{ team.TeamName }} </a></li><!-- 10 -->
                    {% endif %}
                {% endfor %}
                <li class="former-team"><a href="javascript:void(0);">历史项目组</a>
                    <div class="arrow"></div>
                    <ul class="former-team-list">
                    {% for team in teams %}
                        {% if team.OutofTime is True%}
                            <li><a href="/teams/major={{ team.id }}/">{{ team.TeamName }} </a></li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                </li>
                {% if perms.RedAnt.add_projectteam %}
                     <li class="lastmenuli"><a href="/teams/operating=new/">添加项目组</a></li>
                 {% endif %}

                </ul>
            </li>
            <li class="dropdown"><a href="javascript:void(0);" data-target="#" class="dropdown-toggle" data-toggle="dropdown">课程展示 <span class="caret"></span></a>
                <ul class="dropdown-menu pull-right">
                    {% for course in courses %}
                    <li class="dropdownmenu"><a href="/courses/major={{ course.id }}/">{{ course.Name }} </a></li>
                    {% endfor %}
                    {% if perms.RedAnt.add_course %}
                    <li class="lastmenuli"><a href="/courses/operating=new/">添加课程</a></li>
                    {% endif %}
                </ul>
            </li>
            {% if user.is_authenticated %}
                <li class="leaf"><a href="/forum/" >论 &nbsp;坛 </a></li>
            {% endif %}
            {% if perms.auth.change_user %}
                <li class="leaf"><a href="/manage/">系统管理 </a><a class="newMailNum" href="">12</a></li>
            {% endif %}
            <li class="last leaf"><a href="/index/#contact" data-target="#" class="dropdown-toggle" data-toggle="dropdown">联系我们 </a>
            </li>
        </ul>
    </div>
</nav>